In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
source_directory="./data/raw/"
data_set=[]
seasons=[]

for x in os.listdir(source_directory):
    data_set.append(x)
    seasons.append(x.strip('.csv'))

data_set.sort()
seasons.sort()

# Create empty dict to keep track of which clubs appear and how many times
club_seasons={}

In [4]:
for x in data_set:
    season_index=data_set.index(x)
    season=seasons[season_index]
    
    # Read in csv as pandas dataframe
    df=pd.read_csv(source_directory+x)
    
    # Isolate club names from dataframe
    club_list=df['HomeTeam'].unique()
    clubs=[]
    
    for i in club_list:
        if i in clubs:
            continue
        else:
            clubs.append(i)

    clubs.sort()
    
    for i in clubs:
        if i in club_seasons:
            club_seasons[i]+=1
        else:
            club_seasons[i]=1
        
    # Track which clubs have played so the values can be added to the 2d array
    match_count= np.zeros((len(clubs),len(clubs)),int)
    
    # Create empty 2d array to hold yellows and reds for each ref
    yc_data = np.zeros((len(clubs),len(clubs)), int)
    
    # Fill the 2d array with the card count for each ref and club
    for i in range(0,len(df['AY'])):
        home_club=df['HomeTeam'][i]
        away_club=df['AwayTeam'][i]
        yc_data[clubs.index(home_club),clubs.index(away_club)]+=df['HY'][i]
        yc_data[clubs.index(away_club),clubs.index(home_club)]+=df['AY'][i]
    
    temp_df=pd.DataFrame(data=yc_data, index=clubs, columns=clubs)
    #temp_df.to_csv(season+'.csv')
    
    if data_set.index(x)==0:
        master_df=temp_df
    else:
        master_df=pd.concat([master_df,temp_df]).groupby(level=0).sum()

In [6]:
club_seasons

{'Arsenal': 11,
 'Aston Villa': 8,
 'Birmingham': 2,
 'Blackburn': 3,
 'Bolton': 3,
 'Burnley': 6,
 'Chelsea': 11,
 'Everton': 11,
 'Fulham': 6,
 'Hull': 4,
 'Liverpool': 11,
 'Man City': 11,
 'Man United': 11,
 'Portsmouth': 1,
 'Stoke': 9,
 'Sunderland': 8,
 'Tottenham': 11,
 'West Ham': 10,
 'Wigan': 4,
 'Wolves': 5,
 'Blackpool': 1,
 'Newcastle': 9,
 'West Brom': 8,
 'Norwich': 5,
 'QPR': 3,
 'Swansea': 7,
 'Reading': 1,
 'Southampton': 8,
 'Cardiff': 2,
 'Crystal Palace': 7,
 'Leicester': 6,
 'Bournemouth': 5,
 'Watford': 5,
 'Middlesbrough': 1,
 'Brighton': 3,
 'Huddersfield': 2,
 'Sheffield United': 1}

In [13]:
master_df

,Arsenal,Aston Villa,Birmingham,Blackburn,Bolton,Burnley,Chelsea,Everton,Fulham,Hull,...,Southampton,Cardiff,Crystal Palace,Leicester,Bournemouth,Watford,Middlesbrough,Brighton,Huddersfield,Sheffield United
Arsenal,0,27.0,6.0,7.0,9.0,9.0,43,37,10.0,11.0,...,21.0,11.0,21.0,19.0,19.0,16.0,3.0,13.0,7.0,5.0
Aston Villa,34,0.0,7.0,9.0,7.0,10.0,42,28,20.0,10.0,...,18.0,1.0,18.0,16.0,9.0,8.0,0.0,4.0,0.0,3.0
Birmingham,10,9.0,0.0,8.0,10.0,5.0,4,7,2.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Blackburn,11,7.0,9.0,0.0,11.0,5.0,7,17,6.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Blackpool,2,5.0,1.0,3.0,4.0,0.0,2,3,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Bolton,10,16.0,7.0,9.0,0.0,3.0,8,12,12.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Bournemouth,21,8.0,0.0,0.0,0.0,9.0,14,6,2.0,1.0,...,12.0,3.0,19.0,16.0,0.0,14.0,1.0,10.0,11.0,4.0
Brighton,12,5.0,0.0,0.0,0.0,7.0,11,9,6.0,0.0,...,9.0,1.0,13.0,10.0,5.0,7.0,0.0,0.0,5.0,3.0
Burnley,27,13.0,1.0,6.0,2.0,0.0,25,23,2.0,12.0,...,11.0,5.0,14.0,16.0,17.0,11.0,9.0,10.0,10.0,2.0
Cardiff,8,1.0,0.0,0.0,0.0,4.0,5,10,5.0,3.0,...,6.0,0.0,5.0,4.0,2.0,1.0,0.0,3.0,4.0,0.0
Chelsea,47,23.0,2.0,7.0,5.0,16.0,0,42,16.0,13.0,...,23.0,6.0,19.0,7.0,12.0,13.0,3.0,7.0,1.0,0.0
Crystal Palace,13,15.0,0.0,0.0,0.0,14.0,24,20,5.0,14.0,...,24.0,4.0,0.0,12.0,28.0,24.0,5.0,9.0,5.0,4.0
Everton,37,21.0,2.0,10.0,4.0,17.0,44,0,11.0,16.0,...,18.0,3.0,21.0,16.0,22.0,10.0,2.0,6.0,9.0,4.0
Fulham,18,12.0,7.0,10.0,6.0,7.0,12,22,0.0,6.0,...,8.0,4.0,8.0,2.0,5.0,4.0,0.0,5.0,5.0,0.0
Huddersfield,9,0.0,0.0,0.0,0.0,6.0,3,6,2.0,0.0,...,4.0,1.0,7.0,6.0,7.0,7.0,0.0,2.0,0.0,0.0
Hull,13,12.0,0.0,4.0,5.0,15.0,14,8,6.0,0.0,...,6.0,2.0,10.0,7.0,3.0,5.0,3.0,0.0,0.0,0.0
Leicester,23,13.0,0.0,0.0,0.0,6.0,13,14,0.0,4.0,...,10.0,2.0,22.0,0.0,18.0,15.0,4.0,9.0,4.0,1.0
Liverpool,33,22.0,3.0,10.0,8.0,9.0,39,35,11.0,7.0,...,23.0,6.0,20.0,19.0,10.0,9.0,0.0,5.0,2.0,1.0
Man City,53,13.0,5.0,8.0,7.0,21.0,48,39,7.0,13.0,...,28.0,3.0,20.0,21.0,17.0,7.0,5.0,3.0,5.0,4.0
Man United,47,25.0,5.0,5.0,2.0,22.0,55,35,10.0,14.0,...,25.0,6.0,24.0,23.0,16.0,16.0,2.0,5.0,6.0,3.0
Middlesbrough,2,0.0,0.0,0.0,0.0,5.0,4,3,0.0,2.0,...,6.0,0.0,2.0,7.0,3.0,5.0,0.0,0.0,0.0,0.0
Newcastle,26,22.0,4.0,8.0,4.0,13.0,30,36,16.0,8.0,...,15.0,3.0,23.0,16.0,15.0,13.0,0.0,10.0,8.0,2.0
Norwich,20,20.0,0.0,3.0,1.0,1.0,17,15,10.0,2.0,...,8.0,5.0,10.0,7.0,8.0,10.0,0.0,3.0,0.0,0.0
Portsmouth,2,0.0,6.0,5.0,3.0,6.0,3,0,4.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
QPR,17,9.0,0.0,4.0,3.0,3.0,6,10,6.0,5.0,...,7.0,0.0,5.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
Reading,2,2.0,0.0,0.0,0.0,0.0,3,4,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Sheffield United,6,3.0,0.0,0.0,0.0,1.0,2,4,0.0,0.0,...,2.0,0.0,5.0,3.0,3.0,3.0,0.0,3.0,0.0,0.0
Southampton,26,13.0,0.0,0.0,0.0,9.0,43,29,10.0,11.0,...,0.0,7.0,17.0,12.0,16.0,17.0,4.0,12.0,6.0,1.0
Stoke,26,17.0,5.0,11.0,7.0,13.0,42,33,18.0,17.0,...,20.0,5.0,21.0,14.0,9.0,13.0,6.0,0.0,5.0,0.0
Sunderland,34,28.0,4.0,11.0,8.0,14.0,32,21,15.0,18.0,...,17.0,7.0,16.0,16.0,10.0,5.0,4.0,0.0,0.0,0.0
Swansea,20,18.0,0.0,1.0,4.0,9.0,30,29,6.0,9.0,...,12.0,2.0,14.0,10.0,15.0,8.0,2.0,2.0,4.0,0.0
Tottenham,56,20.0,5.0,5.0,3.0,13.0,56,38,12.0,14.0,...,28.0,7.0,23.0,24.0,16.0,12.0,1.0,8.0,6.0,2.0
Watford,24,10.0,0.0,0.0,0.0,13.0,27,22,4.0,2.0,...,17.0,2.0,30.0,16.0,28.0,0.0,4.0,4.0,7.0,3.0
West Brom,27,27.0,2.0,4.0,9.0,9.0,39,28,5.0,6.0,...,22.0,2.0,22.0,12.0,13.0,11.0,2.0,0.0,5.0,0.0
West Ham,41,21.0,9.0,9.0,5.0,20.0,44,35,13.0,13.0,...,25.0,5.0,29.0,21.0,22.0,12.0,3.0,7.0,3.0,2.0
Wigan,15,11.0,11.0,8.0,12.0,1.0,12,19,13.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Wolves,20,16.0,10.0,10.0,9.0,9.0,21,13,15.0,0.0,...,10.0,3.0,11.0,8.0,10.0,6.0,0.0,1.0,3.0,1.0

In [12]:
master_df.describe()

,Arsenal,Aston Villa,Birmingham,Blackburn,Bolton,Burnley,Chelsea,Everton,Fulham,Hull,...,Southampton,Cardiff,Crystal Palace,Leicester,Bournemouth,Watford,Middlesbrough,Brighton,Huddersfield,Sheffield United
count,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,...,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000
mean,21.405405,13.081081,3.000000,4.729730,4.000000,8.756757,22.270270,19.243243,7.675676,6.621622,...,11.756757,2.864865,12.675676,9.810811,9.675676,7.621622,1.702703,3.810811,3.270270,1.216216
std,14.842618,8.479971,3.431877,4.045908,3.734226,6.034187,17.439815,12.850433,5.612754,5.770381,...,9.292785,2.750375,9.407603,7.640673,8.370099,6.188481,2.221922,4.040337,3.322053,1.583511
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,10.000000,7.000000,0.000000,0.000000,0.000000,5.000000,6.000000,8.000000,2.000000,2.000000,...,4.000000,0.000000,5.000000,3.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,20.000000,13.000000,2.000000,5.000000,4.000000,9.000000,17.000000,19.000000,6.000000,5.000000,...,10.000000,2.000000,14.000000,10.000000,9.000000,7.000000,0.000000,3.000000,3.000000,0.000000
75%,27.000000,20.000000,5.000000,8.000000,7.000000,13.000000,39.000000,29.000000,12.000000,12.000000,...,20.000000,5.000000,21.000000,16.000000,16.000000,12.000000,3.000000,7.000000,5.000000,2.000000
max,56.000000,28.000000,11.000000,11.000000,12.000000,22.000000,56.000000,42.000000,20.000000,18.000000,...,28.000000,11.000000,30.000000,24.000000,28.000000,24.000000,9.000000,13.000000,11.000000,5.000000